# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaStateMachine' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MediaStateMachine

  pod 'AFNetworking'
  pod 'CocoaLumberjack'
  
  target 'MediaStateMachineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MediaStateMachine-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MediaStateMachine-tvOS

  target 'MediaStateMachine-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
